### ISSUE TITLE
Combine source files and automate build process

### ISSUE THREAD

**Issue by helgatheviking** [5ally/wpse-332513#1]
Hi Sally! Thanks again for helping with this question!

I noticed that you have a few different source files and they appear to be manually merged.... with instructions to copy/paste. Since I'm also trying to learn some React and the basics of transpiling.... do you think it's possible to write the whole thing as one ES6 file so that it can be automatically built into a js file? 

I'm gonna look at that next since my grunt minify task is failing for some reason on the merged output.

**Comment by helgatheviking** [comment]
Check this out! I kinda did it: https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/blob/dev/src/index.js

But I'm having trouble with adding new terms. And sometimes even with needing to click on the input twice to get it selected. You seeing either of those things in your version?

**Comment by 5ally** [comment]
Hey there,

Sorry, I've just seen your messages less than 24 hours ago.

And I haven't had a chance to look at your code, but check out https://github.com/5ally/my-term-selector and let me know what you think. :)

**Comment by 5ally** [comment]
And if you've got any questions, please use the other repo. I'm closing this issue and - soon - this repo as well.
